export default {
 addApplication: 'Dodaj cv',
 employeeDashboard: 'Panel pracownika',
 chooseAJobApplication: 'Wybierz cv',
 recommendedOffers: 'Rekomendowane oferty pracy',
 noOffers: 'Brak ofert',
 jobApplicationDetails: 'Szczegóły aplikacji',
 skills: 'Umiejętności',
 languages: "Języki",
 certificates: "Certyfikaty",
 profession: 'Zawód',
 category: 'Kategoria',
 back: 'Wstecz',
 certificatesAreAnAdvantage: "Certifikaty są zaletą",
 certificatesAreNotAnAdvantage: "Certifikaty nie są zaletą",
};
