export default {
  titleError: 'prosimy podać tytuł',
  email: 'prosimy o wprowadzenie poprawnego adresu e-mail',
  password: 'prosimy o podanie hasła',
  passwordLength: 'hasło musi zawierać co najmniej 8 znaków',
  surname: 'prosimy o podanie nazwiska',
  name : 'prosimy o podanie imienia',
  userType: 'prosimy o wprowadzenie typu użytkownika ',
  passwordConfirmation: 'potwierdzenie hasła musi pasować do hasła',
  skill: 'prosimy o podanie umiejętności',
  skillLevel: 'prosimy o padnie stopnia zaawansowania',
  repeatedSkill: 'taka umiejętność już została dodana',
  company: 'prosimy o podanie nazwy firmy',
  role: 'prosimy o podanie stanowiska',
  description: 'prosimy o podanie obowiązków i osiągnięć',
  startDate: 'prosimy o podanie daty rozpoczęcia',
  finishDate: 'prosimy o podanie daty zakończenia',
  wrongDate: 'data rozpoczęcia powinna być mniejsza niż data zakończenia',
  certificateName: 'prosimy o podanie nazwy certyfikatu',
  repeatedCertification: 'taki certifikat już został dodany',
  wrongCertificationDate: 'nieprawidłowa data'
};
