export const SET_APPLICATION_REGULAR_FIELD = 'SET_APPLICATION_REGULAR_FIELD';
export const SET_APPLICATION_SKILL = 'SET_APPLICATION_SKILL';
export const REMOVE_APPLICATION_SKILL = 'REMOVE_APPLICATION_SKILL';
export const CLEAN_APPLICATION_DATA = 'CLEAN_APPLICATION_DATA';
export const SET_APPLICATION_LANGUAGE = 'SET_APPLICATION_LANGUAGE';
export const REMOVE_APPLICATION_LANGUAGE = 'REMOVE_APPLICATION_LANGUAGE';
export const SET_APPLICATION_CERTIFICATE = 'SET_APPLICATION_CERTIFICATE';
export const REMOVE_APPLICATION_CERTIFICATE = 'REMOVE_APPLICATION_CERTIFICATE';
