export const SET_APPLICATION_CATEGORY = 'SET_APPLICATION_CATEGORY';
export const SET_APPLICATION_PROFESSION = 'SET_APPLICATION_PROFESSION';
export const SET_APPLICATION_SKILL = 'SET_APPLICATION_SKILL';
export const REMOVE_APPLICATION_SKILL = 'REMOVE_APPLICATION_SKILL';
export const CLEAN_APPLICATION_SKILLS = 'CLEAN_APPLICATION_SKILLS';
export const SET_APPLICATION_LANGUAGE = 'SET_APPLICATION_LANGUAGE';
export const REMOVE_APPLICATION_LANGUAGE = 'REMOVE_APPLICATION_LANGUAGE';
