export const SET_REGULAR_FIELD_CVB = 'SET_REGULAR_FIELD_CVB';
export const ADD_SKILL = 'ADD_SKILL';
export const REMOVE_SKILL = 'REMOVE_SKILL';
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const REMOVE_EXPERIENCE = 'REMOVE_EXPERIENCE';
