export const GET_JOB_APPLICATIONS = 'GET_JOB_APPLICATIONS';
export const SET_JOB_APPLICATIONS = 'SET_JOB_APPLICATIONS';
export const SET_LOADING_JOB_APPLICATIONS = 'SET_LOADING_JOB_APPLICATIONS';
export const SET_JOB_APPLICATION = 'SET_JOB_APPLICATION';
