export const SET_OFFER_CATEGORY = 'SET_OFFER_CATEGORY';
export const SET_OFFER_PROFESSION = 'SET_OFFER_PROFESSION';
export const SET_OFFER_REQUIRED_SKILL = 'SET_OFFER_REQUIRED_SKILL';
export const REMOVE_OFFER_REQUIRED_SKILL= 'REMOVE_OFFER_REQUIRED_SKILL';
export const SET_OFFER_WELCOME_SKILL = 'SET_OFFER_WELCOME_SKILL';
export const REMOVE_OFFER_WELCOME_SKILL = 'REMOVE_OFFER_WELCOME_SKILL';
export const SET_OFFER_LANGUAGE = 'SET_OFFER_LANGUAGE';
export const REMOVE_OFFER_LANGUAGE = 'REMOVE_OFFER_LANGUAGE';

